flowchart LR
    Subj[Select Subject] --> Class[Select Class/Form]
    Class --> Strand[Select Strand]
    Strand --> SubStrand[Select Sub-Strand]
    SubStrand --> CS[Select Content Standard]
    CS --> LO[Select Learning Outcome]
    LO --> LI[Select Learning Indicator]
    LI --> Done([Curriculum alignment complete])