export const ErrorCode = {
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL: "INTERNAL",
  AI_UNAVAILABLE: "AI_UNAVAILABLE",
  AI_INVALID_OUTPUT: "AI_INVALID_OUTPUT",
  AI_RATE_LIMITED: "AI_RATE_LIMITED",
  AI_TIMEOUT: "AI_TIMEOUT",
  AI_REQUEST_FAILED: "AI_REQUEST_FAILED",
  AI_CURRICULUM_INELIGIBLE: "AI_CURRICULUM_INELIGIBLE",
  AI_ACTIVITY_DURATION_EXCEEDED: "AI_ACTIVITY_DURATION_EXCEEDED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
